name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apex_dma/offsets.h'
      - 'apex_dma/apexsky/resource/default/offsets.ini'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd apex_dma && ./build.sh
